on: push
jobs:
  cicd:
    uses: internetarchive/cicd/cicd.yml@main
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
    with:
      NOMAD_VAR_HOSTNAMES: '["wordsmith.dev.archive.org","wordsmith.archive.org"]'
