on: [push, workflow_dispatch]
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
    with:
      NOMAD_VAR_HOSTNAMES: '["wordsmith.dev.archive.org","wordsmith.archive.org"]'
